#.travis.yml

language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - npm run ci-test
  - npm run ci-coveralls
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run ci-deploy; fi

notifications:
  email:
    on_failure: change

sudo: required